# This is a basic workflow to help you get started with Actions

name: Deploy Logic App Code into qa or prod

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use - qa or prod'
        required: true
        default: 'qa'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  logic_app_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Rename parameters file
      run: (mv ./LogicAppStd/parameters.json ./LogicAppStd/parameters.local.json; mv ./LogicAppStd/parameters-azure.json ./LogicAppStd/parameters.json)            
    - name: Package logic app
      run: (cd LogicAppStd; mkdir -p ../output; zip -r ../output/logic.zip .)
    - name: Upload app zip package
      uses: actions/upload-artifact@v4
      with:
        name: logic
        path: ./output/ 
        retention-days: 1
  
  logic_app_deploy: 
    name: Deploy QA or PROD
    runs-on: ubuntu-latest
    needs: [logic_app_build]
    steps: 
    - name: Checkout
      uses: actions/checkout@v3  
    - name: Login via Az module
      uses: azure/login@v2
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
    - uses: actions/download-artifact@v4
      with:
        name: logic
        path: ./output/
    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ format('{0}-{1}-rg', vars.PROJECT_NAME, github.event.inputs.environment) }} `
              -Name ${{ format('{0}-{1}-std-la', vars.PROJECT_NAME, github.event.inputs.environment) }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "profile=$profile" >> $GITHUB_OUTPUT
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.5.1
      id: la
      with:
        app-name: ${{ format('{0}-{1}-std-la', vars.PROJECT_NAME, github.event.inputs.environment) }}
        package: './output/logic.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}       

  